### ISSUE TITLE
Modulo de seguridad Agregar un check box

### ISSUE THREAD

**Issue by DavidGalvanDom** [DavidGalvanDom/CMI-Track#2]
Agregar la funcionalidad para seleccionar todos los módulos de un usuario

**Comment by juanlopepe** [comment]
Ya lo hice en momentos de iluminacion mental y ocio en Educafin inge. Lo tengo para enviartelo. Saludos

**Comment by DavidGalvanDom** [comment]
Ok muchas gracias ya incluí sus cambios
