### ISSUE TITLE
Usuario logueado

### ISSUE THREAD

**Issue by juanlopepe** [DavidGalvanDom/CMI-Track#6]
Nunca sabemos quien es el usuario que esta logueado, Propongo pongamos en el icono del usuario arriba a la derecha que se vea el usuario conectado, ya que para hacer pruebas con dos navegadores de usuarios que tienen diferente proceso de avance, nunca se cual es cual.

Saludos

**Comment by DavidGalvanDom** [comment]
Listo ya se agrego
