### ISSUE TITLE
Integracion general

### ISSUE THREAD

**Issue by DavidGalvanDom** [DavidGalvanDom/CMI-Track#7]
1 Tipo proceso Estatus muestra  1
2. Categorias  muestra  1
~~3. Ruta de fabricacion no muestra categori ni proceso~~
~~4. Integrar registro de calidad~~
~~5. HistoricoAvances el registro del idSeria esta en 0 y debe estar 00~~
~~6. Ver lo de las fechas para los reportes~~
7. url imagen Requerimiento  quitar 95% revision reportes de david jasso
8. Nuevo Materiales catalogo no carga info
9. Catalogo de Origen es Inicial y otro complemento
10. Catalogo de Origenes Requisicion muestra 1 en Estatus
11. Requisicion Manual de Compra  al momento de Autorizar / Rechazar ocultar botones o recargar
12 Tipo de Movimientos proceso Estatus muestra  1
13 Movimeintos Materiales 
    Ocultar Imprimir
    Combo mostrar descripcion en tipo de movimiento
14. Actulizar Material Requisicion Manual no muestra Almacen y Unidad de Medida
15. Movimiento Materiales hay que hacer el Insert en cmiInventarios al momento de agregar una entrada a nuevo material
~~16. Juan Hacer conculta para el obtener el proceso actual en las ordenes de embarque.~~

**Comment by juanlopepe** [comment]
Agrego aqui la consulta para el punto 16

```
/* Consulta para obtener el proceso final
 donde se encuentran las marcas a embarcar */

DECLARE @IdProyecto INT = 1 -- Este viene como parametro de entrada al SP
DECLARE @IdProcesoFinal INT

SELECT @IdProcesoFinal = RF.idProceso
FROM cmiProyectos P
INNER JOIN cmiRutasFabricacion RF ON RF.idCategoria = P.idCategoria
WHERE P.idProyecto = @IdProyecto
    AND RF.secuenciaRutaFabricacion = (SELECT MAX(secuenciaRutaFabricacion)
                                        FROM cmiRutasFabricacion RF2
                                        WHERE RF2.idCategoria = P.idCategoria)

/* Luego usas la variable @IdProcesoFinal para 
    tu filtro de las marcas que se encuentran en ese proceso */
```

**Comment by DavidGalvanDom** [comment]
Se atendieron los puntos
