### ISSUE TITLE
Errores detectados

### ISSUE THREAD

**Issue by juanlopepe** [DavidGalvanDom/CMI-Track#8]
1- El archivo Todos.StoredProcedures devuelve un error al ejecutarse ("No se utiliza ya fue removido el que se utiliza es  usp_InsertarMaterialesProyectoM"

> Msg  207, Level 16, State 1, Procedure usp_InsertarMaterialesProyecto, Line 5883 El nombre de columna 'idOrigenRequisicion' no es válido.

2- Al intentar insertar un Plano de Despiece y no hay un Tipo de Construccion seleccionado devuelve un error no controlado.

**Comment by DavidGalvanDom** [comment]
Se corrigieron los dos puntos
